cluster_name  = "discord-bot-cluster"
cpu           = "512"
memory        = "1024"
desired_count = "1"
region_id     = "eu-north-1"
table_name    = "discord-table"
queue_name    = "discord-bot-queue"